"""add missing columns to users table

Revision ID: add_missing_user_columns
Revises: 
Create Date: 2026-02-03 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_missing_user_columns'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add student_number column (nullable first to handle existing data)
    op.add_column('users', sa.Column('student_number', sa.String(length=8), nullable=True))
    
    # Add other missing columns
    op.add_column('users', sa.Column('id_number', sa.String(length=13), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('profile_picture_data', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_type', sa.String(length=50), nullable=True))
    
    # Update existing rows with default values (optional - remove if you want to handle manually)
    op.execute("UPDATE users SET student_number = '00000000' WHERE student_number IS NULL")
    op.execute("UPDATE users SET id_number = '0000000000000' WHERE id_number IS NULL")
    op.execute("UPDATE users SET phone_number = '0000000000' WHERE phone_number IS NULL")
    
    # Now make columns non-nullable if required
    op.alter_column('users', 'student_number', nullable=False)
    op.alter_column('users', 'id_number', nullable=False)
    op.alter_column('users', 'phone_number', nullable=False)
    
    # Create unique constraints
    op.create_unique_constraint('uq_users_student_number', 'users', ['student_number'])
    op.create_unique_constraint('uq_users_id_number', 'users', ['id_number'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_id_number', 'users', type_='unique')
    op.drop_constraint('uq_users_student_number', 'users', type_='unique')
    op.drop_column('users', 'profile_picture_type')
    op.drop_column('users', 'profile_picture_data')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'id_number')
    op.drop_column('users', 'student_number')
    # ### end Alembic commands ###